[package]
name = "igmnes"
version = "0.1.0"
edition = "2018"
authors = ["Ivan Đorđević <blashyrk92@gmail.com>"]

[dependencies]
sdl2 = { version = "0.38.0", features = ["bundled"] }
rfd = "0.14.0"

[dependencies.nom]
version = "^2.0"
features = ["verbose-errors"]

[profile.release]
debug = true